name       : luit
version    : 1.1.1
release    : 2
source     :
    - https://www.x.org/releases/individual/app/luit-1.1.1.tar.gz : 87b0be0bd01f3b857a53e6625bdd31cef18418c95394b7f4387f8ecef78e45da
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications luit
description: |
    X.Org Applications luit
builddeps  :
    - pkgconfig(fontenc)
    - util-macros
rundeps    :
    - pkgconfig(fontenc)
setup      : |
    patch -Np1 < $pkgfiles/fix-compilation.diff
    %reconfigure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
